server:
	rm -f *.o server
	g++ server.cpp -o server

client:
	rm -f *.o client
	g++ client.cpp -o client

all: 
	rm -f *.o server
	rm -f *.o client
	g++ server.cpp -o server
	g++ client.cpp -o client

clean:
	rm -f *.o server
	rm -f *.o client